trigger: none

pool:
  name: abhi_agent

stages:

- stage: terraformvalidate
  displayName: Terraform Init and Validate

  jobs:
  - job: terraform_init_validate
    displayName: Terraform Init and Validate

    steps:

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendServiceArm: 'abhi_azure_connection'
        backendAzureRmOverrideSubscriptionID: 'cf72e154-d368-4a84-87cf-577efd0a8880'
        backendAzureRmResourceGroupName: 'dev-backend'
        backendAzureRmStorageAccountName: 'devstrgaks'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'vms/terraform.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'


- stage: terraformplan
  displayName: Terraform Plan

  jobs:
  - job: terraform_plan
    displayName: Plan Job

    steps:

    - task: TerraformTask@5
      displayName: Terraform Init for Plan
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        backendServiceArm: 'abhi_azure_connection'
        backendAzureRmOverrideSubscriptionID: 'cf72e154-d368-4a84-87cf-577efd0a8880'
        backendAzureRmResourceGroupName: 'dev-backend'
        backendAzureRmStorageAccountName: 'devstrgaks'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'vms/terraform.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
        environmentServiceNameAzureRM: 'abhi_azure_connection'